#!/usr/bin/env node
/* Generates island/data.js from lib/data.ts so the island can never drift from
   the 2D site. Node 24 strips the TypeScript types on import. Hero and About
   copy live in their components, so they are mirrored here by hand. */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { projects, articles, approachItems, socialLinks } from '../lib/data.ts';

const PROJECTS = projects.map((p) => ({ name: p.title, ...p }));

const DATA = {
  hero: {
    name: 'Marcus Wong',
    tagline: 'I build AI products that close the gap between capability and adoption, and invest across agent infrastructure and vertical applications.',
  },
  stats: [
    { value: "Berkeley '26", label: 'Data Science & Economics', blurb: "UC Berkeley '26, studying Data Science and Economics." },
    { value: 'Llama Ventures', label: 'Investor', blurb: 'Investor at Llama Ventures, a $300M+ early-stage fund backing AI-focused founders.' },
    { value: 'Anthropic', label: 'Previously', blurb: 'Previously an Anthropic Campus Ambassador at UC Berkeley.' },
    { value: 'DoorDash', label: 'Previously', blurb: 'Previously at DoorDash.' },
  ],
  guide: {
    name: 'Marcus',
    pages: [
      "Hi, I'm Marcus. Welcome to my island! Every project I've built has a house here.",
      'Walk with WASD or the arrow keys, drag to look around, and scroll to zoom. When a bubble appears, press E.',
      "Featured builds are up the north road, side projects off to the east. The boards cover how I work, the newsstand has my writing, and the mailbox is how to reach me. Talk to me again any time for the longer story.",
    ],
  },
  about: [
    "I've spent two years at the intersection of AI product development and user adoption.",
    "As an Anthropic Campus Ambassador at UC Berkeley, I led a team that drove 10,000+ Claude Pro signups and built programming reaching 40,000+ students. I ran the frontline of how students discover and use Claude — organizing workshops, hackathons, and demos for hundreds of students. That work gives me pattern recognition most builders don't have: I see what excites new users, what confuses them, and where the gap between a model's capabilities and someone's actual workflow becomes a wall.",
    "At SJF Ventures, I built AI tools for investors who had never touched a terminal — Salesforce automations, intelligent search engines for deal sourcing, and portfolio monitoring systems. I provided similar technical assistance and advice to its portfolio companies in healthcare, education, and government, including developing some prototypes for new AI features. The constraint was the same: if the person using this can't understand it in 30 seconds, it doesn't matter how good the code is.",
    "Now I'm an investor at Llama Ventures, a $300M+ early-stage fund backing AI-focused founders. I bring a builder's lens to diligence — prototyping alongside founders, pressure-testing product decisions, and spotting the gap between a model's capabilities and a real workflow before anyone else does.",
    "On the side, I keep building. I prototype fast, test with real users, and iterate the same night. Every project here started with a pattern I noticed and a question I couldn't stop thinking about.",
  ],
  contact: {
    title: "Let's talk.",
    email: 'marcusmhwong@gmail.com',
  },
};

const out =
  '/* GENERATED by gen-data.mjs from lib/data.ts — do not edit by hand */\n' +
  `const PROJECTS = ${JSON.stringify(PROJECTS, null, 2)};\n` +
  `const ARTICLES = ${JSON.stringify(articles, null, 2)};\n` +
  `const APPROACH = ${JSON.stringify(approachItems, null, 2)};\n` +
  `const SOCIAL = ${JSON.stringify(socialLinks, null, 2)};\n` +
  `const DATA = ${JSON.stringify(DATA, null, 2)};\n`;

writeFileSync(fileURLToPath(new URL('./data.js', import.meta.url)), out);
console.log(`✓ data.js — ${PROJECTS.length} projects, ${articles.length} articles`);
